version: '3.5'
networks:
  casino-streaming:
    name: casino-streaming
    driver: bridge
services:
  influxdb:
    image: influxdb:1.6-alpine
    container_name: influxdb
    ports:
    - "8086:8086"
    environment:
    - INFLUXDB_DB=sensors
    - INFLUXDB_USER=admin
    - INFLUXDB_USER_PASSWORD=admin
    networks:
    - casino-streaming
  grafana:
    image: grafana/grafana:5.3.1
    container_name: grafana
    ports:
    - "3000:3000"
    volumes:
    - ./env/grafana/provisioning:/etc/grafana/provisioning
    - ./env/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
    - casino-streaming
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    expose:
    - 2181
    networks:
    - casino-streaming
  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.3
    container_name: kafka
    ports:
    - '9092:9092'
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
    networks:
    - casino-streaming
  jobmanager:
    image: flink:1.6-alpine
    container_name: jobmanager
    ports:
    - "8081:8081"
    command: jobmanager
    environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
    - casino-streaming
  taskmanager:
    image: flink:1.6-alpine
    container_name: taskmanager
    expose:
    - "6121"
    - "6122"
    depends_on:
    - jobmanager
    command: taskmanager
    links:
    - "jobmanager:jobmanager"
    environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
    - casino-streaming