version: '3.5'
networks:
  casino-streaming:
    name: casino-streaming
    driver: bridge
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1
    container_name: elasticsearch
    ports:
    - "9200:9200"
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    networks:
    - casino-streaming
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.1
    container_name: kibana
    ports:
    - "5601:5601"
    networks:
    - casino-streaming
  elasticsearch_dump:
    image: taskrabbit/elasticsearch-dump:v4.1.2
    container_name: elasticsearch_dump
    networks:
    - casino-streaming
    volumes:
    - ./env/elasticdump:/var/elasticdump
    entrypoint:
    - sh
    - /var/elasticdump/dump.sh
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    ports:
    - '2181:2181'
    networks:
    - casino-streaming
  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.3
    container_name: kafka
    ports:
    - '9092:9092'
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
    networks:
    - casino-streaming