version: '3'
services:
  influxdb:
    image: influxdb:1.6-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_USER=admin
      - INFLUXDB_USER_PASSWORD=admin
  grafana:
    image: grafana/grafana:5.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./env/grafana/provisioning:/etc/grafana/provisioning
      - ./env/grafana/dashboards:/var/lib/grafana/dashboards
  zookeeper:
    image: bitnami/zookeeper:3.4.12
    container_name: zookeeper
    expose:
    - 2181
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:2.0.0
    container_name: kafka
    ports:
    - '9092:9092'
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
  jobmanager:
    image: flink:1.6-alpine
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  taskmanager:
    image: flink:1.6-alpine
    container_name: taskmanager
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager