{
 "title": "Casino",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Site income",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_siteId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "siteId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "site_profit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Game income",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_gameId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "gameId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "game_profit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Machine income",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_machineId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "machineId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "machine_profit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}